export { official }

const official = {
  'ad': [ 'ca' ],
  'ae': [ 'ar-ae' ],
  'af': [ 'fa-af', 'ps-af' ],
  'ag': [ 'en-ag' ],
  'ai': [ 'en-ai' ],
  'al': [ 'sq' ],
  'am': [ 'hy' ],
  'an': [ 'nl-an', 'en', 'pap' ],
  'ao': [ 'pt-ao' ],
  'aq': [ ],
  'ar': [ 'es-ar' ],
  'as': [ 'sm', 'en-as' ],
  'at': [ 'de-at' ],
  'au': [ 'en-au' ],
  'aw': [ 'nl-aw', 'pap' ],
  'ax': [ 'sv-ax' ],
  'az': [ 'az' ],
  'ba': [ 'bs', 'hr', 'sr-ba' ],
  'bb': [ 'en-bb' ],
  'bd': [ 'bn-bd' ],
  'be': [ 'nl-be', 'fr-be', 'de-be' ],
  'bf': [ 'fr-bf' ],
  'bg': [ 'bg' ],
  'bh': [ 'ar-bh' ],
  'bi': [ 'fr-bi', 'rn' ],
  'bj': [ 'fr-bj' ],
  'bl': [ 'fr-bl' ],
  'bm': [ 'en-bm' ],
  'bn': [ 'ms-bn' ],
  'bo': [ 'es-bo' ],
  'bq': [ 'nl-bq' ],
  'br': [ 'pt-br' ],
  'bs': [ 'en-bs' ],
  'bt': [ 'dz' ],
  'bv': [ ],
  'bw': [ 'en-bw', 'tn' ],
  'by': [ 'be', 'ru' ],
  'bz': [ 'en-bz' ],
  'ca': [ 'en-ca', 'fr-ca' ],
  'cc': [ 'en-cc' ],
  'cd': [ 'fr-cd' ],
  'cf': [ 'fr-cf', 'sg' ],
  'cg': [ 'fr-cg' ],
  'ch': [ 'de-ch', 'fr-ch', 'it-ch', 'rm' ],
  'ci': [ 'fr-ci' ],
  'ck': [ 'en-ck' ],
  'cl': [ 'es-cl' ],
  'cm': [ 'fr-cm', 'en-cm' ],
  'cn': [ 'zh-cn' ],
  'co': [ 'es-co' ],
  'cr': [ 'es-cr' ],
  'cu': [ 'es-cu' ],
  'cv': [ 'pt-cv' ],
  'cw': [ 'nl-cw' ],
  'cx': [ 'en-cx' ],
  'cy': [ 'el-cy', 'tr-cy' ],
  'cz': [ 'cs' ],
  'de': [ 'de-de' ],
  'dj': [ 'fr-dj', 'ar-dj' ],
  'dk': [ 'da-dk' ],
  'dm': [ 'en-dm' ],
  'do': [ 'es-do' ],
  'dz': [ 'ar-dz' ],
  'ec': [ 'es-ec' ],
  'ee': [ 'et' ],
  'eg': [ 'ar-eg' ],
  'eh': [ 'ar-eh' ],
  'er': [ 'ti', 'ar-er' ],
  'es': [ 'es-es' ],
  'et': [ 'am' ],
  'fi': [ 'fi', 'sv-fi' ],
  'fj': [ 'en-fj' ],
  'fk': [ 'en-fk' ],
  'fm': [ 'en-fm' ],
  'fo': [ 'fo', 'da-fo' ],
  'fr': [ 'fr-fr' ],
  'ga': [ 'fr-ga' ],
  'gb': [ 'en-gb' ],
  'gd': [ 'en-gd' ],
  'ge': [ 'ka' ],
  'gf': [ 'fr-gf' ],
  'gg': [ 'en-gg' ],
  'gh': [ 'en-gh' ],
  'gi': [ 'en-gi' ],
  'gl': [ 'kl', 'da-gl' ],
  'gm': [ 'en-gm' ],
  'gn': [ 'fr-gn' ],
  'gp': [ 'fr-gp' ],
  'gq': [ 'es-gq', 'fr-gq', 'pt-gq' ],
  'gr': [ 'el-gr' ],
  'gs': [ 'en' ],
  'gt': [ 'es-gt' ],
  'gu': [ 'en-gu', 'ch-gu' ],
  'gw': [ 'pt-gw' ],
  'gy': [ 'en-gy' ],
  'hk': [ 'zh-hk', 'en-hk' ],
  'hm': [ ],
  'hn': [ 'es-hn' ],
  'hr': [ 'hr' ],
  'ht': [ 'fr-ht', 'ht' ],
  'hu': [ 'hu' ],
  'id': [ 'id' ],
  'ie': [ 'en-ie' ],
  'il': [ 'he', 'ar-il' ],
  'im': [ 'en-im' ],
  'in': [ 'hi', 'en-in' ],
  'io': [ 'en-io' ],
  'iq': [ 'ar-iq' ],
  'ir': [ 'fa-ir' ],
  'is': [ 'is' ],
  'it': [ 'it-it' ],
  'je': [ 'en-je' ],
  'jm': [ 'en-jm' ],
  'jo': [ 'ar-jo' ],
  'jp': [ 'ja' ],
  'ke': [ 'en-ke', 'sw-ke' ],
  'kg': [ 'ky', 'ru' ],
  'kh': [ 'km' ],
  'ki': [ 'en-ki' ],
  'km': [ 'ar-km', 'fr-km' ],
  'kn': [ 'en-kn' ],
  'kp': [ 'ko-kp' ],
  'kr': [ 'ko-kr' ],
  'kw': [ 'ar-kw' ],
  'ky': [ 'en-ky' ],
  'kz': [ 'kk', 'ru' ],
  'la': [ 'lo' ],
  'lb': [ 'ar-lb' ],
  'lc': [ 'en-lc' ],
  'li': [ 'de-li' ],
  'lk': [ 'si', 'ta-lk' ],
  'lr': [ 'en-lr' ],
  'ls': [ 'en-ls', 'st' ],
  'lt': [ 'lt' ],
  'lu': [ 'fr-lu', 'de-lu', 'lb' ],
  'lv': [ 'lv' ],
  'ly': [ 'ar-ly' ],
  'ma': [ 'ar-ma' ],
  'mc': [ 'fr-mc' ],
  'md': [ 'ro', 'ru' ],
  'me': [ 'sr-me' ],
  'mf': [ 'fr-mf' ],
  'mg': [ 'fr-mg', 'mg' ],
  'mh': [ 'en-mh', 'mh' ],
  'mk': [ 'mk' ],
  'ml': [ 'fr-ml' ],
  'mm': [ 'my' ],
  'mn': [ 'mn' ],
  'mo': [ 'zh-mo', 'pt-mo' ],
  'mp': [ 'ch-mp', 'en-mp' ],
  'mq': [ 'fr-mq' ],
  'mr': [ 'ar-mr' ],
  'ms': [ 'en-ms' ],
  'mt': [ 'mt', 'en-mt' ],
  'mu': [ 'mfe', 'en-mu', 'fr-mu' ],
  'mv': [ 'dv' ],
  'mw': [ 'en-mw', 'ny' ],
  'mx': [ 'es-mx' ],
  'my': [ 'ms-my' ],
  'mz': [ 'pt-mz' ],
  'na': [ 'en-na' ],
  'nc': [ 'fr-nc' ],
  'ne': [ 'fr-ne' ],
  'nf': [ 'en-nf' ],
  'ng': [ 'en-ng' ],
  'ni': [ 'es-ni' ],
  'nl': [ 'nl-nl' ],
  'no': [ 'no', 'nb', 'nn' ],
  'np': [ 'ne' ],
  'nr': [ 'na', 'en-nr' ],
  'nu': [ 'niu', 'en-nu' ],
  'nz': [ 'en-nz' ],
  'om': [ 'ar-om' ],
  'pa': [ 'es-pa' ],
  'pe': [ 'es-pe' ],
  'pf': [ 'fr-pf' ],
  'pg': [ 'en-pg' ],
  'ph': [ 'en-ph' ],
  'pk': [ 'ur-pk', 'en-pk' ],
  'pl': [ 'pl' ],
  'pm': [ 'fr-pm' ],
  'pn': [ 'en-pn' ],
  'pr': [ 'es-pr', 'en-pr' ],
  'ps': [ 'ar-ps' ],
  'pt': [ 'pt-pt' ],
  'pw': [ 'en-pw' ],
  'py': [ 'es-py', 'gn' ],
  'qa': [ 'ar-qa' ],
  're': [ 'fr-re' ],
  'ro': [ 'ro' ],
  'rs': [ 'sr-rs' ],
  'ru': [ 'ru' ],
  'rw': [ 'rw', 'fr-rw', 'en-rw' ],
  'sa': [ 'ar-sa' ],
  'sb': [ 'en-sb' ],
  'sc': [ 'fr-sc', 'en-sc', 'crs' ],
  'sd': [ 'ar-sd' ],
  'se': [ 'sv-se' ],
  'sg': [ 'en-sg', 'zh-sg', 'ms-sg', 'ta-sg' ],
  'sh': [ 'en-sh' ],
  'si': [ 'sl' ],
  'sj': [ 'no', 'ru' ],
  'sk': [ 'sk' ],
  'sl': [ 'en-sl' ],
  'sm': [ 'it-sm' ],
  'sn': [ 'fr-sn' ],
  'so': [ 'so-so', 'ar-so' ],
  'sr': [ 'nl-sr' ],
  'ss': [ 'en-ss' ],
  'st': [ 'pt-st' ],
  'sv': [ 'es-sv' ],
  'sx': [ 'nl-sx', 'en-sx' ],
  'sy': [ 'ar-sy' ],
  'sz': [ 'en-sz', 'ss' ],
  'tc': [ 'en-tc' ],
  'td': [ 'fr-td', 'ar-td' ],
  'tf': [ 'fr-tf' ],
  'tg': [ 'fr-tg' ],
  'th': [ 'th' ],
  'tj': [ 'tg', 'ru' ],
  'tk': [ 'tkl', 'en-tk' ],
  'tl': [ 'pt-tl', 'tet' ],
  'tm': [ 'tk' ],
  'tn': [ 'ar-tn' ],
  'to': [ 'to', 'en-to' ],
  'tr': [ 'tr' ],
  'tt': [ 'en-tt' ],
  'tv': [ 'en-tv', 'tvl' ],
  'tw': [ 'zh-tw' ],
  'tz': [ 'sw-tz', 'en-tz' ],
  'ua': [ 'uk', 'ru' ],
  'ug': [ 'en-ug', 'sw-ug' ],
  'um': [ 'en-um' ],
  'us': [ 'en-us' ],
  'uy': [ 'es-uy' ],
  'uz': [ 'uz', 'ru' ],
  'va': [ 'la', 'it' ],
  'vc': [ 'en-vc' ],
  've': [ 'es-ve' ],
  'vg': [ 'en-vg' ],
  'vi': [ 'en-vi' ],
  'vn': [ 'vi' ],
  'vu': [ 'bi', 'en-vu', 'fr-vu' ],
  'wf': [ 'fr-wf' ],
  'ws': [ 'sm', 'en-ws' ],
  'xk': [ 'sq', 'sr' ],
  'ye': [ 'ar-ye' ],
  'yt': [ 'fr-yt' ],
  'za': [ 'af', 'en-za', 'zu', 'xh' ],
  'zm': [ 'en-zm' ],
  'zw': [ 'en-zw' ]
}